### ISSUE TITLE
Login Fails because Signup didn't create any user.

### ISSUE THREAD

**Issue by Angelizo1** [daniccan/multi-tenant-node-app#10]
When attempting to login from postman, it returns a 400 error code with msg "Login Failed". Checking the database I noticed that signup didn't generate and consequently save the user on its corresponding "Users" table even though the call for the user creation is there inside the signup data provider that gets executed when performing a signup from postman.

![image](https://user-images.githubusercontent.com/66858449/158860168-e1c8f574-8536-47d1-8740-1e1829e1e81a.png)

What's interesting is that the promise for the "userDataProvider.createUser" doesn't return a reject as one would expect. Also I noticed that the User model has a foregin key dependency to an organization id. And based on the code the payload object for the user isn't receiving it.

UPDATE: I was able to filter out the error. It seems the query field for "organizationId" is somehow changed to start with capital O as described here. Also I manually created this user by inserting it directly into the database so that's the reason I'm trying to use this data.
![image](https://user-images.githubusercontent.com/66858449/158894926-424f0fd9-e491-43af-9563-ebe2ff9e30fd.png)

I will keep trying to debug this issue in the hopes of finding a proper fix for it. Also If I'm missing anything let me know. Thanks.

**Comment by daniccan** [comment]
You will have to pass the `X-TENANT-ID` header for APIs other than Sign Up. 

Reference: https://github.com/daniccan/multi-tenant-node-app/blob/master/README.md#http-headers
