### ISSUE TITLE
facing issue at the time of installing packages

### ISSUE THREAD

**Issue by jatinchandani28** [daniccan/multi-tenant-node-app#8]
after extracting I had tried to install packages through npm install but the errors are coming

**Comment by miguelpicocecropiasolution** [comment]
I am also getting the same errors. Couldn't run npm install, it showed errors referring to <node-pre-gyp>. Does anyone else know how to solve this ?

**Comment by daniccan** [comment]
Upgraded to the latest node and npm versions.

https://github.com/daniccan/multi-tenant-node-app/commit/21c396560e13e941a509659626d14467c85193da
